language: python

python:

  - "3.6"

virtualenv:
  system_site_packages: true

install:
  - apt install python-pip
  - pip install -r requirements/dev.txt

script: 

  - ./scripts/install.sh
  - python scripts/app.py

