sudo: required
language: python

python:

  - "3.6"

virtualenv:
  - system_site_packages: true

before_install:

  - apt install python-pip
  - pip install -r requirements/dev.txt

install:

  - ./scripts/install.sh

script: 

  - python scripts/app.py

